
version: '3.7'

services:
  roon-server:
    build: docker/roon-server
    image: steefdebruijn/docker-roonserver
    container_name: roon-server
    network_mode: "host"
    restart: unless-stopped
    init: true
    environment:
      - TZ="Europe/Amsterdam"
    volumes:
      - roon-app:/app
      - roon-data:/data
      - /home/smangels/projects/docker-roonserver/music:/music
      - roon-backups:/backup

volumes:
  roon-app:
  roon-data:
  roon-backups:
